#!/bin/bash
set -ex
source "$(dirname "${0}")/build/init.sh"
source ${PYTHON_FOLDER}/venv/bin/activate
nightly_data="${WORKSPACE_FOLDER}/data/dummy_data_nightly_move_candidate.bin"
if [ ! -f ${nightly_data} ]; then
    echo "File not found! path=${nightly_data}. This file has to be provided manually to perform nightly test. (File is not part of the repo by default as it is too large. It can be generated by dummy_data_generator_move_candidate.)"
    exit 1
fi
output_root_dir="${BUILD_DATA_FOLDER}/dummy_nnue_nightly_move_candidate"
rm -rf ${output_root_dir}
train_command_line="${nightly_data} ${nightly_data} move_candidate --gpus "0," --threads 4 --num-workers 4 --batch-size 4096 --lambda=1.0 --max_epochs=5 --default_root_dir ${output_root_dir}"
python3 ${PYTHON_FOLDER}/nnuepytorch/train.py ${train_command_line}
output_nnue_path="${output_root_dir}/dummy_nightly_move_candidate.nnue"
python3 ${PYTHON_FOLDER}/nnuepytorch/serialize.py ${output_root_dir}/lightning_logs/version_0/checkpoints/last.ckpt ${output_nnue_path} move_candidate
echo "dummy_nightly_move_candidate.nnue generated. path=${output_nnue_path}"

nightly_data="${WORKSPACE_FOLDER}/data/dummy_data_nightly_eval.bin"
if [ ! -f ${nightly_data} ]; then
    echo "File not found! path=${nightly_data}. This file has to be provided manually to perform nightly test. (File is not part of the repo by default as it is too large. It can be generated by dummy_data_generator_eval.)"
    exit 1
fi
output_root_dir="${BUILD_DATA_FOLDER}/dummy_nnue_nightly_eval"
rm -rf ${output_root_dir}
train_command_line="${nightly_data} ${nightly_data} eval --gpus "0," --threads 4 --num-workers 4 --batch-size 4096 --lambda=1.0 --max_epochs=5 --default_root_dir ${output_root_dir}"
python3 ${PYTHON_FOLDER}/nnuepytorch/train.py ${train_command_line}
output_nnue_path="${output_root_dir}/dummy_nightly_eval.nnue"
python3 ${PYTHON_FOLDER}/nnuepytorch/serialize.py ${output_root_dir}/lightning_logs/version_0/checkpoints/last.ckpt ${output_nnue_path} eval
echo "dummy_nightly_eval.nnue generated. path=${output_nnue_path}"

